apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: collab-spreadsheet
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "2401301024"
  JWT_SECRET: "c2VjdXJlLXByb2R1Y3Rpb24tMjU2LWJpdC1zZWNyZXQta2V5LXBsZWFzZS1jaGFuZ2UtdGhpcw=="
